import React from 'react';
import { Route } from 'react-router';
 
export default (
    <Route>
		  <Route exact path='/home' />
		  <Route exact path='/dissertations'/>
		  <Route exact path='/themes'/>
		  <Route exact path='/philosophes'/>
		  <Route exact path='/rating' />	

			<Route exact path='/theme/art/'/>
			<Route exact path='/theme/autrui/'/>
			<Route exact path='/theme/bonheur/'/>
			<Route exact path='/theme/conscience/'/>
			<Route exact path='/theme/corps/'/>
			<Route exact path='/theme/culture/'/>
			<Route exact path='/theme/désir/'/>
			<Route exact path='/theme/devoir/'/>
			<Route exact path='/theme/droit/'/>
			<Route exact path='/theme/échanges/'/>
			<Route exact path='/theme/État/'/>
			<Route exact path='/theme/histoire/'/>
			<Route exact path='/theme/idée/'/>
			<Route exact path='/theme/illusion/'/>
			<Route exact path='/theme/imagination/'/>
			<Route exact path='/theme/inconscient/'/>
			<Route exact path='/theme/jugement/'/>
			<Route exact path='/theme/justice/'/>
			<Route exact path='/theme/langage/'/>
			<Route exact path='/theme/liberté/'/>
			<Route exact path='/theme/logique/'/>
			<Route exact path='/theme/morale/'/>
			<Route exact path='/theme/mémoire/'/>
			<Route exact path='/theme/métaphysique/'/>
			<Route exact path='/theme/mort/'/>
			<Route exact path='/theme/nature/'/>
			<Route exact path='/theme/passions/'/>
			<Route exact path='/theme/pouvoir/'/>
			<Route exact path='/theme/politique/'/>
			<Route exact path='/theme/religion/'/>
			<Route exact path='/theme/science/'/>
			<Route exact path='/theme/sens/'/>
			<Route exact path='/theme/technique/'/>
			<Route exact path='/theme/temps/'/>
			<Route exact path='/theme/travail/'/>
			<Route exact path='/theme/vérité/'/>
			<Route exact path='/theme/violence/'/>
			<Route exact path='/theme/volonté/'/>
			
			<Route exact path='/philosophe/Alain (philosophe)/'/>
			<Route exact path='/philosophe/Alexis de_Tocqueville/'/>
			<Route exact path='/philosophe/Anselme de_Canterbury/'/>
			<Route exact path='/philosophe/Antoine Cournot/'/>
			<Route exact path='/philosophe/Aristote/'/>
			<Route exact path='/philosophe/Arthur Schopenhauer/'/>
			<Route exact path='/philosophe/Auguste Comte/'/>
			<Route exact path='/philosophe/Averroes/'/>
			<Route exact path='/philosophe/Baruch Spinoza/'/>
			<Route exact path='/philosophe/Benoît de_Maillet/'/>
			<Route exact path='/philosophe/Bernard_Le_Bouyer de_Fontenelle/'/>
			<Route exact path='/philosophe/Bertrand Russell/'/>
			<Route exact path='/philosophe/Blaise Pascal/'/>
			<Route exact path='/philosophe/Cesar_Chesneau Dumarsais/'/>
			<Route exact path='/philosophe/Charles_Marie de_La_Condamine/'/>
			<Route exact path='/philosophe/Ciceron/'/>
			<Route exact path='/philosophe/Comte_de Buffon/'/>
			<Route exact path='/philosophe/David Hume/'/>
			<Route exact path='/philosophe/Denis Diderot/'/>
			<Route exact path='/philosophe/Edmund Husserl/'/>
			<Route exact path='/philosophe/Emile Durkheim/'/>
			<Route exact path='/philosophe/Emmanuel Kant/'/>
			<Route exact path='/philosophe/Epicure/'/>
			<Route exact path='/philosophe/Etienne_Bonnot de_Condillac/'/>
			<Route exact path='/philosophe/Francis Bacon/'/>
			<Route exact path='/philosophe/Friedrich Nietzsche/'/>
			<Route exact path='/philosophe/Gaston Bachelard/'/>
			<Route exact path='/philosophe/Georg Hegel/'/>
			<Route exact path='/philosophe/George Berkeley/'/>
			<Route exact path='/philosophe/Giambattista Vico/'/>
			<Route exact path='/philosophe/Gottfried_Wilhelm Leibniz/'/>
			<Route exact path="/philosophe/Guillaume d'Occam/"/>
			<Route exact path='/philosophe/Hannah Arendt/'/>
			<Route exact path='/philosophe/Jean Meslier/'/>
			<Route exact path='/philosophe/Jean-Jacques Rousseau/'/>
			<Route exact path='/philosophe/Jean-Paul Sartre/'/>
			<Route exact path='/philosophe/Jeremy Bentham/'/>
			<Route exact path='/philosophe/John Locke/'/>
			<Route exact path='/philosophe/John Rawls/'/>
			<Route exact path='/philosophe/John_Stuart Mill/'/>
			<Route exact path='/philosophe/Karl Popper/'/>
			<Route exact path='/philosophe/Louis de_Jaucourt/'/>
			<Route exact path='/philosophe/Ludwig Wittgenstein/'/>
			<Route exact path='/philosophe/Martin Heidegger/'/>
			<Route exact path='/philosophe/Michel de_Montaigne/'/>
			<Route exact path='/philosophe/Michel Foucault/'/>
			<Route exact path='/philosophe/Montesquieu/'/>
			<Route exact path='/philosophe/Nicolas Machiavel/'/>
			<Route exact path='/philosophe/Nicolas Malebranche/'/>
			<Route exact path='/philosophe/Pierre Bayle/'/>
			<Route exact path='/philosophe/Platon/'/>
			<Route exact path='/philosophe/Plotin/'/>
			<Route exact path='/philosophe/Rene Descartes/'/>
			<Route exact path='/philosophe/Saint Augustin/'/>
			<Route exact path='/philosophe/Sextus Empiricus/'/>
			<Route exact path='/philosophe/Sigmund Freud/'/>
			<Route exact path='/philosophe/Søren Kierkegaard/'/>
			<Route exact path='/philosophe/Stoiciens/'/>
			<Route exact path="/philosophe/Thomas d'aquin/"/>
			<Route exact path='/philosophe/Thomas Hobbes/'/>
			<Route exact path='/philosophe/Voltaire/'/>
    </Route>
);